
version: '1.0'

services:
  mynginx:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
    restart: always
